language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_script:
  - npm prune
script:
  - npm test
  - npm run build
after_success:
  - npm run publish:all
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
