language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '7'
  - '6'
before_script:
  - npm prune
script:
  - npm test
  - npm run build
after_success:
  - npm run publish:all
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: "${TRAVIS_BUILD_DIR}/build"
  on:
    branch: develop
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
