language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_install:
  - printf "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
before_script:
  - npm prune
script:
  - npm test
  - npm run build
after_success:
  - git pull --rebase
  - npm run publish:all
  - npm run storybook:build
  - npm run deploy
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
